### PR TITLE
Create NeedIt Application Module Completed

### PR DESCRIPTION
**Pull request by tuanhphung**

### CODE REVIEW

**Comment by tuanhphung** [comment]
ok

**Comment by tuanhphung** [comment]
c

**Comment by bsweets** [comment]
Thanks for submitting this, but we do not accept pull requests against the ServiceNow training primary repository. If you want to access your specific work from a learning module, we recommend that you do not merge the changes into the primary repository. If you still want to merge, please select **your fork** as the *base repository* in GitHub before making the pull request.

**Comment by tuanhphung** [comment]
Hi Ben,

Apologies for the pull, that was a mistake on my part.
At the moment I am having issues importing the forked repo to ServiceNow (which was working yesterday)
________________________________

**Comment by bsweets** [comment]
No worries. You only need to import once. If you have already imported, you can move on to the create branch exercise for the learning module.

**Pull request closed without merging**
