### PR TITLE
Create NeedIt Application Module Completed

### PR DESCRIPTION
**Pull request by jungjun-lim**

### CODE REVIEW

**Comment by jungjun-lim** [comment]
commit

**Comment by bsweets** [comment]
Thanks for submitting this, but we do not accept pull requests against the ServiceNow training primary repository. If you want to access your specific work from a learning module, we recommend that you do not merge the changes into the primary repository. If you still want to merge, please select **your fork** as the *base repository* in GitHub before making the pull request.

**Comment by jungjun-lim** [comment]
> Thanks for submitting this, but we do not accept pull requests against the ServiceNow training primary repository. If you want to access your specific work from a learning module, we recommend that you do not merge the changes into the primary repository. If you still want to merge, please select **your fork** as the _base repository_ in GitHub before making the pull request.

It was my mistake. Sorry for inconvenience.

**Comment by bsweets** [comment]
No worries! I just wanted you to be aware of the reason your pull request won't be merged. I hope you are enjoying the learning content!
Ben

**Pull request closed without merging**
